### ISSUE TITLE
Fetching images and uploading to an image bucket

### ISSUE THREAD

**Issue by kiliczsh** [kiliczsh/sandik#13]
@BYK @egeakman after @shazar has shared full database we can try to obtain images from urls, what do you think?

**Comment by egeakman** [comment]
> @BYK @egeakman after @shazar has shared full database we can try to obtain images from urls, what do you think?

It looks feasible.

- What bucket do you think we should use? GDrive, OneDrive, or simply S3?
- How is the file structure going to be? I think city/district/ballot_num.jpg is good.
- Do you know a way to upload the images to the bucket directly, without downloading them in the first place? (Like a POST request with the URL of the image to the bucket's API) (Lambda + API Gateway + S3 might be a solution for that)

*Update:*
The URLs are changed so we need to modify the old ones while using them:

```python
url = "https://secim-images.oyveotesi.org/oyveotesi/blurred-min/server/" + url.split('/')[-1]
```

**Comment by BYK** [comment]
We can also look into [Cloudflare R2](https://developers.cloudflare.com/r2/)

**Comment by egeakman** [comment]
Clearing up my  `mentioned me` pile
